# 系统配置信息
server:
  name: airbbs
  host: localhost
  port: 8080
#  数据库配置信息
database:
  host: 127.0.0.1
  port: 3306
  dbname: airbbs
  username: codermast
  password: 123456
# JWT 配置信息
jwt:
  signing_key: "jwt_key_golangnotes"
  header: "Authorization"
  secret: "jwt_key_golangnotes"
  issuer: "air_bbs"
  subject : "test"
  expire_hours: 24
# Redis 配置信息
redis:
  host: localhost
  port: 6379
  db: 0
  password: