# 系统配置信息
system:
  name:
    airblog
#  数据库配置信息
database:
  host: localhost
  port: 3306
  dbname: airblog
  username: codermast
  password: 123456
# JWT 配置信息
jwt:
  signing_key: "jwt_key_golangnotes"
  header: "Authorization"
  secret: "jwt_key_golangnotes"
  issuer: "air_blog"
  subject : "test"
  expire_hours: 24
